# Generated by Django 2.2.7 on 2019-11-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flores',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='flor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petalos.Categoria')),
            ],
        ),
    ]
